"""
Session and Message models for Agentic AI Tutor.
Handles stateful conversations and chat history storage.
"""

import uuid
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from sqlalchemy import Column, String, DateTime, Text, Boolean, Integer, ForeignKey, JSON
from sqlalchemy.orm import relationship
import logging

from app.core.database import Base

logger = logging.getLogger(__name__)


class Session(Base):
    """
    Session model representing a conversation session between student and AI tutor.

    Sessions maintain context across multiple interactions and enable stateful conversations
    for better personalization and learning continuity.
    """

    __tablename__ = "sessions"

    # Primary identification
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))

    # Student relationship
    student_id = Column(String, ForeignKey("students.id"), nullable=False, index=True)
    student = relationship("Student", back_populates="sessions")

    # Session state management
    is_active = Column(Boolean, default=True, nullable=False)
    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    last_interaction = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Session metadata and context
    session_type = Column(
        String(50), default="general", nullable=False
    )  # general, quiz, review, etc.
    current_topic = Column(String(100), nullable=True)  # Current learning topic
    session_goals = Column(JSON, nullable=True, default=list)  # List of learning objectives

    # Agent context and state
    agent_state = Column(JSON, nullable=True, default=dict)  # Current agent workflow state
    conversation_summary = Column(Text, nullable=True)  # AI-generated session summary

    # Performance tracking for this session
    questions_asked = Column(Integer, default=0, nullable=False)
    questions_answered_correctly = Column(Integer, default=0, nullable=False)
    topics_covered = Column(JSON, nullable=True, default=list)  # Topics discussed in this session

    # Relationships
    messages = relationship(
        "Message",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="Message.timestamp",
    )

    def __init__(self, **kwargs):
        """Initialize session with default values"""
        super().__init__(**kwargs)

        if not self.session_goals:
            self.session_goals = []
        if not self.agent_state:
            self.agent_state = {
                "last_agent_used": None,
                "workflow_step": "initial",
                "context_summary": None,
                "pending_actions": [],
            }
        if not self.topics_covered:
            self.topics_covered = []

    @property
    def duration_minutes(self) -> float:
        """
        Calculate session duration in minutes.

        Returns:
            float: Duration in minutes, or current duration if session is active
        """
        end_time = self.ended_at or datetime.utcnow()
        duration = end_time - self.started_at
        return duration.total_seconds() / 60

    @property
    def accuracy_percentage(self) -> float:
        """
        Calculate question accuracy for this session.

        Returns:
            float: Accuracy as percentage (0-100)
        """
        if self.questions_asked == 0:
            return 0.0
        return (self.questions_answered_correctly / self.questions_asked) * 100

    @property
    def is_expired(self) -> bool:
        """
        Check if session has expired (60 minutes of inactivity).

        Returns:
            bool: True if session should be considered expired
        """
        if not self.is_active:
            return True

        expiry_time = self.last_interaction + timedelta(minutes=60)
        return datetime.utcnow() > expiry_time

    def update_interaction(self) -> None:
        """Update the last interaction timestamp"""
        self.last_interaction = datetime.utcnow()

    def end_session(self, summary: Optional[str] = None) -> None:
        """
        End the session and optionally store a summary.

        Args:
            summary: Optional session summary generated by AI
        """
        self.is_active = False
        self.ended_at = datetime.utcnow()
        if summary:
            self.conversation_summary = summary

        logger.info(f"Session {self.id} ended after {self.duration_minutes:.1f} minutes")

    def add_topic_covered(self, topic: str) -> None:
        """
        Add a topic to the list of topics covered in this session.

        Args:
            topic: Topic name to add
        """
        if not self.topics_covered:
            self.topics_covered = []

        if topic not in self.topics_covered:
            self.topics_covered.append(topic)
            logger.debug(f"Added topic '{topic}' to session {self.id}")

    def update_agent_state(self, state_updates: Dict[str, Any]) -> None:
        """
        Update the agent workflow state.

        Args:
            state_updates: Dictionary of state updates to merge
        """
        if not self.agent_state:
            self.agent_state = {}

        self.agent_state.update(state_updates)
        logger.debug(f"Updated agent state for session {self.id}")

    def get_recent_messages(self, limit: int = 10) -> List["Message"]:
        """
        Get recent messages from this session.

        Args:
            limit: Maximum number of messages to return

        Returns:
            List[Message]: Recent messages ordered by timestamp
        """
        return sorted(self.messages, key=lambda m: m.timestamp, reverse=True)[:limit]

    def get_conversation_context(self, max_messages: int = 20) -> List[Dict[str, Any]]:
        """
        Get conversation context for agent processing.

        Args:
            max_messages: Maximum number of recent messages to include

        Returns:
            List[Dict]: Messages formatted for LLM consumption
        """
        recent_messages = self.get_recent_messages(max_messages)
        recent_messages.reverse()  # Oldest first for chronological order

        context = []
        for message in recent_messages:
            context.append(
                {
                    "role": message.role,
                    "content": message.content,
                    "timestamp": message.timestamp.isoformat(),
                    "metadata": message.message_metadata or {},
                }
            )

        return context

    def __repr__(self):
        status = "Active" if self.is_active else "Ended"
        return f"<Session(id='{self.id}', student_id='{self.student_id}', status='{status}')>"

    def __str__(self):
        return f"Session {self.id[:8]} - {self.duration_minutes:.1f}min - {len(self.messages)} messages"


class Message(Base):
    """
    Message model representing individual chat messages in a conversation session.

    Stores both user questions and AI tutor responses with metadata for analysis.
    """

    __tablename__ = "messages"

    # Primary identification
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Session relationship
    session_id = Column(String, ForeignKey("sessions.id"), nullable=False, index=True)
    session = relationship("Session", back_populates="messages")

    # Message content and metadata
    role = Column(String(20), nullable=False, index=True)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Message classification and context
    message_type = Column(
        String(50), default="chat", nullable=False
    )  # chat, quiz, explanation, etc.
    topic = Column(String(100), nullable=True, index=True)  # Related topic if identified

    # Additional metadata (JSON for flexibility)
    message_metadata = Column(JSON, nullable=True, default=dict)  # Agent info, confidence, etc.

    def __init__(self, **kwargs):
        """Initialize message with default message metadata"""
        super().__init__(**kwargs)

        if not self.message_metadata:
            self.message_metadata = {}

    @classmethod
    def create_user_message(
        cls,
        session_id: str,
        content: str,
        message_type: str = "chat",
        topic: Optional[str] = None,
        message_metadata: Optional[Dict[str, Any]] = None,
    ) -> "Message":
        """
        Create a new user message.

        Args:
            session_id: Session ID this message belongs to
            content: User's message content
            message_type: Type of message (chat, question, etc.)
            topic: Related topic if known
            message_metadata: Additional metadata

        Returns:
            Message: New user message instance
        """
        return cls(
            session_id=session_id,
            role="user",
            content=content,
            message_type=message_type,
            topic=topic,
            message_metadata=message_metadata or {},
        )

    @classmethod
    def create_assistant_message(
        cls,
        session_id: str,
        content: str,
        message_type: str = "response",
        topic: Optional[str] = None,
        agent_info: Optional[Dict[str, Any]] = None,
        message_metadata: Optional[Dict[str, Any]] = None,
    ) -> "Message":
        """
        Create a new assistant message.

        Args:
            session_id: Session ID this message belongs to
            content: Assistant's response content
            message_type: Type of message (response, explanation, etc.)
            topic: Related topic
            agent_info: Information about which agents were used
            message_metadata: Additional metadata

        Returns:
            Message: New assistant message instance
        """
        message_metadata = message_metadata or {}
        if agent_info:
            message_metadata["agent_info"] = agent_info

        return cls(
            session_id=session_id,
            role="assistant",
            content=content,
            message_type=message_type,
            topic=topic,
            message_metadata=message_metadata,
        )

    def add_agent_metadata(self, agent_name: str, agent_data: Dict[str, Any]) -> None:
        """
        Add metadata about which agent processed this message.

        Args:
            agent_name: Name of the agent (planner, retriever, etc.)
            agent_data: Agent-specific data (confidence, sources, etc.)
        """
        if not self.message_metadata:
            self.message_metadata = {}

        if "agents_used" not in self.message_metadata:
            self.message_metadata["agents_used"] = {}

        self.message_metadata["agents_used"][agent_name] = agent_data

    def get_word_count(self) -> int:
        """
        Get word count of message content.

        Returns:
            int: Number of words in the message
        """
        return len(self.content.split()) if self.content else 0

    def is_question(self) -> bool:
        """
        Simple heuristic to determine if message is a question.

        Returns:
            bool: True if message appears to be a question
        """
        if not self.content:
            return False

        question_indicators = ["?", "how", "what", "why", "when", "where", "who", "explain", "help"]
        content_lower = self.content.lower()

        return self.content.strip().endswith("?") or any(
            indicator in content_lower for indicator in question_indicators
        )

    def __repr__(self):
        content_preview = self.content[:50] + "..." if len(self.content) > 50 else self.content
        return f"<Message(id={self.id}, role='{self.role}', content='{content_preview}')>"

    def __str__(self):
        timestamp_str = self.timestamp.strftime("%H:%M:%S")
        content_preview = self.content[:100] + "..." if len(self.content) > 100 else self.content
        return f"[{timestamp_str}] {self.role}: {content_preview}"
